// Data-driven tables for grounds and entities.
// Source of truth: the game's builtins.py (`Grounds`, `Entities`) and docs/unlocks/*.md.
// To add an entity (e.g. for a future DLC) append a row to ENTITIES; everything else
// (palette, export/import, validation, renderers, URL codec) is derived from these tables.
// NOTE: the URL codec derives codes from table order, so append new rows at the END.

export const GROUNDS = [
  {
    name: "Grassland",
    label: "Grassland",
    shortcut: "g",
    description: "The default ground. Grass grows on it automatically.",
  },
  {
    name: "Soil",
    label: "Soil",
    shortcut: "s",
    description: "Created by till(). Required for carrots, pumpkins, cacti and sunflowers.",
  },
];

export const DEFAULT_GROUND = "Grassland";

// Per-tile parameters. `key` is the stored name; `py` is the key used in the Python export.
export const PARAMS = {
  cactusSize: { key: "cactusSize", py: "size", label: "Cactus size", min: 0, max: 9, default: 9 },
  petals: { key: "petals", py: "petals", label: "Petals", min: 7, max: 15, default: 15 },
};

// category: "plant" = can be planted with plant(); "special" = generated by the game, view-only.
// grounds: grounds the entity can exist on. If it can't be on Grassland, painting it auto-tills.
export const ENTITIES = [
  {
    name: "Grass",
    label: "Grass",
    category: "plant",
    grounds: ["Grassland", "Soil"],
    shortcut: "w",
    description: "Grows on grassland or soil. Harvest for hay.",
  },
  {
    name: "Bush",
    label: "Bush",
    category: "plant",
    grounds: ["Grassland", "Soil"],
    shortcut: "b",
    description: "Small shrub. Harvest for wood.",
  },
  {
    name: "Tree",
    label: "Tree",
    category: "plant",
    grounds: ["Grassland", "Soil"],
    shortcut: "t",
    description: "Gives more wood. Grows slower next to other trees (N/E/S/W).",
  },
  {
    name: "Carrot",
    label: "Carrot",
    category: "plant",
    grounds: ["Soil"],
    shortcut: "c",
    description: "Needs soil.",
  },
  {
    name: "Pumpkin",
    label: "Pumpkin",
    category: "plant",
    grounds: ["Soil"],
    shortcut: "p",
    description: "Needs soil. Full squares of grown pumpkins merge into a giant pumpkin.",
  },
  {
    name: "Cactus",
    label: "Cactus",
    category: "plant",
    grounds: ["Soil"],
    shortcut: "k",
    param: "cactusSize",
    description: "Needs soil. Size 0–9; sorted fields harvest together.",
  },
  {
    name: "Sunflower",
    label: "Sunflower",
    category: "plant",
    grounds: ["Soil"],
    shortcut: "u",
    param: "petals",
    description: "Needs soil. 7–15 petals; harvest the one with the most for bonus power.",
  },
  {
    name: "Apple",
    label: "Apple",
    category: "special",
    grounds: ["Grassland", "Soil"],
    description: "Dinosaur food (spawned by the game).",
  },
  {
    name: "Dinosaur",
    label: "Dinosaur",
    category: "special",
    grounds: ["Grassland", "Soil"],
    description: "Dinosaur tail segment (spawned by the game).",
  },
  {
    name: "Hedge",
    label: "Hedge",
    category: "special",
    grounds: ["Grassland", "Soil"],
    description: "Maze wall (spawned by the game).",
  },
  {
    name: "Treasure",
    label: "Treasure",
    category: "special",
    grounds: ["Grassland", "Soil"],
    description: "Maze treasure (spawned by the game).",
  },
  {
    name: "Dead_Pumpkin",
    label: "Dead Pumpkin",
    category: "special",
    grounds: ["Grassland", "Soil"],
    description: "A pumpkin that died. Planting over it removes it.",
  },
];

export const ENTITY_BY_NAME = Object.fromEntries(ENTITIES.map((e) => [e.name, e]));
export const GROUND_BY_NAME = Object.fromEntries(GROUNDS.map((g) => [g.name, g]));

export const isEntity = (name) => Object.hasOwn(ENTITY_BY_NAME, name);
export const isGround = (name) => Object.hasOwn(GROUND_BY_NAME, name);

/** True if the entity can't live on Grassland (painting it auto-tills to Soil). */
export const needsSoil = (name) => {
  const e = ENTITY_BY_NAME[name];
  return !!e && !e.grounds.includes("Grassland");
};

export const canGrowOn = (entity, ground) => {
  const e = ENTITY_BY_NAME[entity];
  return !!e && e.grounds.includes(ground);
};

export const clampParam = (paramKey, value) => {
  const p = PARAMS[paramKey];
  const n = Math.round(Number(value));
  if (!Number.isFinite(n)) return p.default;
  return Math.min(p.max, Math.max(p.min, n));
};

// World sizes the farm grows through with the Expand upgrades, plus the minimum
// size accepted by set_world_size(). Any integer between MIN and MAX is allowed.
export const MIN_SIZE = 3;
export const MAX_SIZE = 32;
export const SIZE_PRESETS = [3, 4, 6, 8, 10, 12, 16, 22, 32];
export const DEFAULT_SIZE = 8;
